In [2]:
import pandas as pd

In [8]:
datos = pd.read_csv('steam_games.csv')

C:\Users\felix\AppData\Local\Temp\ipykernel_20576\221274447.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,9,10,11,14,15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  datos = pd.read_csv('steam_games.csv')

In [9]:
datos.head()

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561197970982479,7.656120e+16,"[{'item_id': '10', 'item_name': 'Counter-Strik...",277.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,js41637,7.656120e+16,"[{'item_id': '10', 'item_name': 'Counter-Strik...",888.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,evcentric,7.656120e+16,"[{'item_id': '1200', 'item_name': 'Red Orchest...",137.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Riot-Punch,7.656120e+16,"[{'item_id': '10', 'item_name': 'Counter-Strik...",328.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,doctr,7.656120e+16,"[{'item_id': '300', 'item_name': 'Day of Defea...",541.0

In [10]:
datos.dropna(subset='id', inplace=True)

In [11]:
datos.columns

Index(['publisher', 'genres', 'app_name', 'title', 'url', 'release_date',
       'tags', 'reviews_url', 'discount_price', 'specs', 'price',
       'early_access', 'id', 'metascore', 'developer', 'user_id', 'steam_id',
       'items', 'items_count'],
      dtype='object')

In [12]:
datos.columns

Index(['publisher', 'genres', 'app_name', 'title', 'url', 'release_date',
       'tags', 'reviews_url', 'discount_price', 'specs', 'price',
       'early_access', 'id', 'metascore', 'developer', 'user_id', 'steam_id',
       'items', 'items_count'],
      dtype='object')

In [13]:
data_ml = datos[['id','title','genres','tags','specs','publisher']]

In [14]:
data_ml = data_ml.reset_index(drop=True)

In [15]:
data_ml['genres'][0]

"['Action', 'Casual', 'Indie', 'Simulation', 'Strategy']"

In [16]:
data_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32133 entries, 0 to 32132
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         32133 non-null  float64
 1   title      30084 non-null  object
 2   genres     28851 non-null  object
 3   tags       31971 non-null  object
 4   specs      31464 non-null  object
 5   publisher  24063 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.5+ MB

In [17]:
data_ml['id'].isna().sum()

0

In [18]:
data_ml['id'] = data_ml['id'].astype(int)

In [19]:
data_ml

,id,title,genres,tags,specs,publisher
0,761140,Lost Summoner Kitty,"['Action', 'Casual', 'Indie', 'Simulation', 'S...","['Strategy', 'Action', 'Indie', 'Casual', 'Sim...",['Single-player'],Kotoshiro
1,643980,Ironbound,"['Free to Play', 'Indie', 'RPG', 'Strategy']","['Free to Play', 'Strategy', 'Indie', 'RPG', '...","['Single-player', 'Multi-player', 'Online Mult...","Making Fun, Inc."
2,670290,Real Pool 3D - Poolians,"['Casual', 'Free to Play', 'Indie', 'Simulatio...","['Free to Play', 'Simulation', 'Sports', 'Casu...","['Single-player', 'Multi-player', 'Online Mult...",Poolians.com
3,767400,弹炸人2222,"['Action', 'Adventure', 'Casual']","['Action', 'Adventure', 'Casual']",['Single-player'],彼岸领域
4,773570,NaN,NaN,"['Action', 'Indie', 'Casual', 'Sports']","['Single-player', 'Full controller support', '...",NaN
...,...,...,...,...,...,...
32128,773640,Colony On Mars,"['Casual', 'Indie', 'Simulation', 'Strategy']","['Strategy', 'Indie', 'Casual', 'Simulation']","['Single-player', 'Steam Achievements']",Ghost_RUS Games
32129,733530,LOGistICAL: South Africa,"['Casual', 'Indie', 'Strategy']","['Strategy', 'Indie', 'Casual']","['Single-player', 'Steam Achievements', 'Steam...",Sacada
32130,610660,Russian Roads,"['Indie', 'Racing', 'Simulation']","['Indie', 'Simulation', 'Racing']","['Single-player', 'Steam Achievements', 'Steam...",Laush Studio
32131,658870,EXIT 2 - Directions,"['Casual', 'Indie']","['Indie', 'Casual', 'Puzzle', 'Singleplayer', ...","['Single-player', 'Steam Achievements', 'Steam...",SIXNAILS
32132,681550,NaN,NaN,"['Early Access', 'Adventure', 'Indie', 'Action...","['Single-player', 'Stats', 'Steam Leaderboards...",NaN

In [20]:
# Utilizar str.extract() para extraer el texto fuera de la lista
data_ml['genres'] = data_ml['genres'].str.extract(r"\['(.*?)'\]")
data_ml['tags'] = data_ml['tags'].str.extract(r"\['(.*?)'\]")
data_ml['specs'] = data_ml['specs'].str.extract(r"\['(.*?)'\]")

In [21]:
data_ml['id']

0        761140
1        643980
2        670290
3        767400
4        773570
          ...
32128    773640
32129    733530
32130    610660
32131    658870
32132    681550
Name: id, Length: 32133, dtype: int32

In [22]:
data_ml

,id,title,genres,tags,specs,publisher
0,761140,Lost Summoner Kitty,"Action', 'Casual', 'Indie', 'Simulation', 'Str...","Strategy', 'Action', 'Indie', 'Casual', 'Simul...",Single-player,Kotoshiro
1,643980,Ironbound,"Free to Play', 'Indie', 'RPG', 'Strategy","Free to Play', 'Strategy', 'Indie', 'RPG', 'Ca...","Single-player', 'Multi-player', 'Online Multi-...","Making Fun, Inc."
2,670290,Real Pool 3D - Poolians,"Casual', 'Free to Play', 'Indie', 'Simulation'...","Free to Play', 'Simulation', 'Sports', 'Casual...","Single-player', 'Multi-player', 'Online Multi-...",Poolians.com
3,767400,弹炸人2222,"Action', 'Adventure', 'Casual","Action', 'Adventure', 'Casual",Single-player,彼岸领域
4,773570,NaN,NaN,"Action', 'Indie', 'Casual', 'Sports","Single-player', 'Full controller support', 'HT...",NaN
...,...,...,...,...,...,...
32128,773640,Colony On Mars,"Casual', 'Indie', 'Simulation', 'Strategy","Strategy', 'Indie', 'Casual', 'Simulation","Single-player', 'Steam Achievements",Ghost_RUS Games
32129,733530,LOGistICAL: South Africa,"Casual', 'Indie', 'Strategy","Strategy', 'Indie', 'Casual","Single-player', 'Steam Achievements', 'Steam C...",Sacada
32130,610660,Russian Roads,"Indie', 'Racing', 'Simulation","Indie', 'Simulation', 'Racing","Single-player', 'Steam Achievements', 'Steam T...",Laush Studio
32131,658870,EXIT 2 - Directions,"Casual', 'Indie","Indie', 'Casual', 'Puzzle', 'Singleplayer', 'A...","Single-player', 'Steam Achievements', 'Steam C...",SIXNAILS
32132,681550,NaN,NaN,"Early Access', 'Adventure', 'Indie', 'Action',...","Single-player', 'Stats', 'Steam Leaderboards',...",NaN

In [23]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\felix\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\felix\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\felix\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

nltk.download('stopwords')

# Convertir todas las columnas de texto a minúsculas
data_ml['id'] = data_ml['id'].astype(str).str.lower()
data_ml['genres'] = data_ml['genres'].astype(str).str.lower()
data_ml['tags'] = data_ml['tags'].astype(str).str.lower()
data_ml['specs'] = data_ml['specs'].astype(str).str.lower()
data_ml['publisher'] = data_ml['publisher'].astype(str).str.lower()

# Eliminar caracteres no deseados en todas las columnas
data_ml['genres'] = data_ml['genres'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))
data_ml['tags'] = data_ml['tags'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))
data_ml['specs'] = data_ml['specs'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))
data_ml['publisher'] = data_ml['publisher'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))

# Eliminar palabras vacías (stop words) en todas las columnas
stop_words = set(stopwords.words('english'))
data_ml['genres'] = data_ml['genres'].apply(lambda x: ' '.join([word for word in word_tokenize(x) if word.lower() not in stop_words]))
data_ml['tags'] = data_ml['tags'].apply(lambda x: ' '.join([word for word in word_tokenize(x) if word.lower() not in stop_words]))
data_ml['specs'] = data_ml['specs'].apply(lambda x: ' '.join([word for word in word_tokenize(x) if word.lower() not in stop_words]))
data_ml['publisher'] = data_ml['publisher'].apply(lambda x: ' '.join([word for word in word_tokenize(x) if word.lower() not in stop_words]))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\felix\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
data_ml

,id,title,genres,tags,specs,publisher
0,761140,Lost Summoner Kitty,action casual indie simulation strategy,strategy action indie casual simulation,single player,kotoshiro
1,643980,Ironbound,free play indie rpg strategy,free play strategy indie rpg card game trading...,single player multi player online multi player...,making fun inc
2,670290,Real Pool 3D - Poolians,casual free play indie simulation sports,free play simulation sports casual indie multi...,single player multi player online multi player...,poolians com
3,767400,弹炸人2222,action adventure casual,action adventure casual,single player,
4,773570,NaN,nan,action indie casual sports,single player full controller support htc vive...,nan
...,...,...,...,...,...,...
32128,773640,Colony On Mars,casual indie simulation strategy,strategy indie casual simulation,single player steam achievements,ghost rus games
32129,733530,LOGistICAL: South Africa,casual indie strategy,strategy indie casual,single player steam achievements steam cloud s...,sacada
32130,610660,Russian Roads,indie racing simulation,indie simulation racing,single player steam achievements steam trading...,laush studio
32131,658870,EXIT 2 - Directions,casual indie,indie casual puzzle singleplayer atmospheric r...,single player steam achievements steam cloud,sixnails
32132,681550,NaN,nan,early access adventure indie action simulation vr,single player stats steam leaderboards htc viv...,nan

In [26]:
data_ml['combined_text'] = data_ml['genres'] + ' ' + data_ml['tags'] + ' ' + data_ml['specs'] + ' ' + data_ml['publisher']

In [27]:
data_ml = data_ml[['id','title','combined_text']]

In [28]:
data_ml

,id,title,combined_text
0,761140,Lost Summoner Kitty,action casual indie simulation strategy strate...
1,643980,Ironbound,free play indie rpg strategy free play strateg...
2,670290,Real Pool 3D - Poolians,casual free play indie simulation sports free ...
3,767400,弹炸人2222,action adventure casual action adventure casua...
4,773570,NaN,nan action indie casual sports single player f...
...,...,...,...
32128,773640,Colony On Mars,casual indie simulation strategy strategy indi...
32129,733530,LOGistICAL: South Africa,casual indie strategy strategy indie casual si...
32130,610660,Russian Roads,indie racing simulation indie simulation racin...
32131,658870,EXIT 2 - Directions,casual indie indie casual puzzle singleplayer ...
32132,681550,NaN,nan early access adventure indie action simula...

In [29]:
#data_ml.to_csv('data_ML.csv', index=False)

In [30]:
data_ml = pd.read_csv('data_ML.csv')

In [36]:
data_ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32133 entries, 0 to 32132
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             32133 non-null  int64
 1   title          30084 non-null  object
 2   combined_text  32133 non-null  object
dtypes: int64(1), object(2)
memory usage: 753.2+ KB

In [39]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

vectorizer = TfidfVectorizer(stop_words='english')
vectorized_data = vectorizer.fit_transform(data_ml['combined_text'])

In [40]:
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(vectorized_data)

NearestNeighbors(algorithm='brute', metric='cosine')

In [43]:
# Crear y ajustar el modelo KNN fuera de la función
knn_model = NearestNeighbors(metric='cosine', algorithm='brute')
knn_model.fit(vectorized_data)


def get_recomendations(id, modelo=knn_model):
    data_ml['id'] = data_ml['id'].astype(str)
    # Verificar si el id existe en el DataFrame
    if id not in data_ml['id'].values:
        return {'error': 'ID not found'}
    
    # Obtener índice del id
    index = data_ml[data_ml['id'] == id].index[0]
    
    # Numero de recomendaciones
    num_recomen = 5
    
    # Obtener recomendaciones basadas en el índice de consulta
    _, indices = knn_model.kneighbors(vectorized_data[index], n_neighbors=num_recomen+1)
    
    # Obtener índices de los id recomendadas
    index_id = indices.flatten()[1:]
    
    # Devolver una estructura de diccionario con los IDs de los title recomendadas
    result = {'lista recomendada': data_ml['title'].iloc[index_id].tolist()}

    return result

In [45]:
id = input('Ingrese un id: ')
recomendacion = get_recomendations(id)
print(recomendacion)

{'lista recomendada': ['EXIT', 'EXIT 3 - Painter', 'Bacteria', 'Energy Balance', 'Hexoscope']}